[[AgentConfig]]
Interval = "10s"
RoundInterval = true
Precision = "1s"
CollectionJitter = "10s"
FlushInterval = "10s"
FlushJitter = "10s"
MetricBatchSize = 10000
MetricBufferLimit = 10000
FlushBufferWhenFull = true
Debug = false
Logfile ="log"
Quiet = false
Hostname = ""
OmitHostname = false